import type { DefaultSharedModuleContext, LangiumServices, LangiumSharedServices, Module, PartialLangiumServices } from 'langium';
import { createDefaultModule, createDefaultSharedModule, inject } from 'langium';
import { ArduinoGeneratedModule, ArduinoGeneratedSharedModule } from './generated/module.js';
import { ArduinoValidator, registerValidationChecks } from './arduino-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ArduinoAddedServices = {
    validation: {
        ArduinoValidator: ArduinoValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ArduinoServices = LangiumServices & ArduinoAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ArduinoModule: Module<ArduinoServices, PartialLangiumServices & ArduinoAddedServices> = {
    validation: {
        ArduinoValidator: (services) => new ArduinoValidator(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createArduinoServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Arduino: ArduinoServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ArduinoGeneratedSharedModule
    );
    const Arduino = inject(
        createDefaultModule({ shared }),
        ArduinoGeneratedModule,
        ArduinoModule
    );
    shared.ServiceRegistry.register(Arduino);
    registerValidationChecks(Arduino);
    return { shared, Arduino };
}
